### ISSUE TITLE
Undefined method 'default_formats'

### ISSUE THREAD

**Issue by s19n** [eyp/redmine_spent_time#76]
Redmine 2.5.1 on Ubuntu 14.04, redmine_spent_time 2.6.6:

```
/var/lib/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/lookup_context.rb:55:in `block in <class:LookupContext>': undefined method `default_formats' for Act
ionView::Base:Class (NoMethodError)
        from /var/lib/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/lookup_context.rb:40:in `initialize_details'
        from /var/lib/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/lookup_context.rb:200:in `initialize'
        from /usr/lib/ruby/vendor_ruby/action_view/base.rb:207:in `new'
        from /usr/lib/ruby/vendor_ruby/action_view/base.rb:207:in `initialize'
        from /var/lib/gems/2.0.0/gems/best_in_place-3.0.3/lib/best_in_place/railtie.rb:7:in `new'
        from /var/lib/gems/2.0.0/gems/best_in_place-3.0.3/lib/best_in_place/railtie.rb:7:in `block in <class:Railtie>'
        from /usr/lib/ruby/vendor_ruby/active_support/lazy_load_hooks.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/active_support/lazy_load_hooks.rb:34:in `execute_hook'
        from /usr/lib/ruby/vendor_ruby/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
        from /usr/lib/ruby/vendor_ruby/active_support/lazy_load_hooks.rb:42:in `each'
        from /usr/lib/ruby/vendor_ruby/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
        from /usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:59:in `block in <module:Finisher>'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `each'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
        from /usr/lib/ruby/vendor_ruby/rails/application.rb:136:in `initialize!'
        from /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
        from /usr/share/redmine/config/environment.rb:14:in `<top (required)>'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from /usr/share/redmine/config.ru:3:in `block in <main>'
        from /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `initialize'
        from /usr/share/redmine/config.ru:1:in `new'
        from /usr/share/redmine/config.ru:1:in `<main>'
        from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:36:in `eval'
        from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:36:in `load'
        from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:45:in `for'
        from /usr/lib/ruby/vendor_ruby/thin/controllers/controller.rb:169:in `load_adapter'
        from /usr/lib/ruby/vendor_ruby/thin/controllers/controller.rb:73:in `start'
        from /usr/lib/ruby/vendor_ruby/thin/runner.rb:185:in `run_command'
        from /usr/lib/ruby/vendor_ruby/thin/runner.rb:151:in `run!'
        from /usr/bin/thin:6:in `<main>'
```
Feel free to ask should you need any further detail.

**Comment by eyp** [comment]
best_in_place plugin is not used anymore.

**Comment by s19n** [comment]
* Eduardo Y��ez Parareda <notifications@github.com> [2015 08 05, 11:30]:
> best_in_place plugin is not used anymore.

So redmine_spent_time v2.6.6 is not compatible with Redmine 2.5.1?

Regards,

-- 
https://s19n.net

**Comment by eyp** [comment]
Forget my comment... I deleted it but after send it :(

Yes, it's compatible, or it was working earlier. I didn't change anything on that version.
